name: kazi_core
description: "A package to handle the Kazi core"
version: 0.5.0
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  webview_flutter: ^4.8.0
  get_it: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/images/
    - lib/shared/assets/svgs/

flutter_intl:
  enabled: true
  class_name: KaziLocalizations
  main_locale: en
  arb_dir: lib/shared/l10n/arb
  output_dir: lib/shared/l10n/generated
  use_deferred_loading: false
