name: kazi_core
description: "A package to handle the Kazi core"
version: 0.5.0
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.32.4"

dependencies:
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  webview_flutter: ^4.8.0
  syncfusion_flutter_calendar: ^29.1.38

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/images/
    - lib/shared/assets/svgs/

flutter_intl:
  enabled: true
  class_name: KaziLocalizations
  main_locale: en
  arb_dir: lib/shared/l10n/arb
  output_dir: lib/shared/l10n/generated
  use_deferred_loading: false
