name: kazi_companies
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.4
  kazi_core: 
    git:
      url: https://github.com/lucas-242/kazi_core.git
      ref: 0.5.0
  riverpod_annotation: ^2.6.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true